services:
  app:
    container_name: triopg
    build: .
    volumes:
      - .:/triopg
      - /.venv
      - /.pdm-python
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
